#! /bin/sh

### BEGIN INIT INFO
# Provides:          homebridge
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of Clue HomeBridge
### END INIT INFO

############### EDIT ME ##################

NAME=bridge
DESC="Clue Bridge"
PID_FILE=/var/run/$NAME.pid
LOG_FILE=/var/log/$NAME.log
DAEMON=/usr/bin/node
OPTIONS="/opt/clue/share/bridge/bridge.js --$1 -D"
SETUP="/opt/clue/bin/setup"

############### END EDIT ME ##################

splash=n

test -x $DAEMON || exit 10
test -x $SETUP || exit 0

. /lib/lsb/init-functions

for x in $(cat /proc/cmdline); do
	case $x in
		splash)
			splash=y
			;;
	esac
done

config()
{
	if [ ! -d /root/.homebridge ] || [ ! -h /root/.homebridge/config.json ]; then
		if [ ! -d /root/.homebridge ]; then
			mkdir -p /root/.homebridge
		fi
		if [ ! -f /opt/clue/etc/bridge.json ]; then
			/opt/clue/bin/bridge --config
		fi
		if [ ! -h /root/.homebridge/config.json ]; then
			ln -fs /opt/clue/etc/bridge.json /root/.homebridge/config.json
		fi
	fi

	if [ ! -h /opt/node/lib/node_modules/homebridge-clue ]; then
		if [ ! -d /opt/node/lib/node_modules ]; then
			mkdir -p /opt/node/lib/node_modules
		fi
		ln -fs /opt/clue/share/bridge /opt/node/lib/node_modules/homebridge-clue
	fi
}

case "$1" in
	start)
		log_daemon_msg "Starting $DESC" "$NAME"
		if [ $(ps -ef | grep "init splash setup" | grep -v "grep" | wc -l) -eq 0 ]; then
			config
			start-stop-daemon --start --background --pidfile $PID_FILE --chuid root --make-pidfile \
				--exec /bin/bash -- -c "exec $DAEMON $OPTIONS > $LOG_FILE 2>&1"

			log_end_msg $?

			if [ "$splash" = "y" ] && [ "$(/sbin/runlevel | cut -d " " -f 2)" != "unknown" ] && [ "$(/sbin/runlevel | cut -d " " -f 2)" != "" ]; then
				$SETUP --splash --info
			fi
		else
			log_progress_msg "Service won't start because the system is still in [setup] mode"
			log_end_msg 1
		fi
		;;
	stop)
		log_daemon_msg "Stopping $DESC" "$NAME"
		start-stop-daemon --stop --pidfile $PID_FILE --startas $DAEMON -- $OPTIONS

		log_end_msg $?
		rm -f $PID_FILE

		if [ "$splash" = "y" ] && [ "$(/sbin/runlevel | cut -d " " -f 2)" != "unknown" ] && [ "$(/sbin/runlevel | cut -d " " -f 2)" != "" ] && [ $(ps -ef | grep "bridge" | grep -v "grep" | grep -v "apt" | grep -v "dpkg" | wc -l) -ne 0 ]; then
			$SETUP --splash --info
		fi
		;;
	restart)
		$0 stop && sleep 2 && $0 start
		;;
	status)
		status_of_proc $DAEMON "$DESC"
		;;
	showpin)
		/opt/clue/bin/bridge --display
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart|config|reconfig|display}"
		exit 1
		;;
esac
