#!/bin/bash

if [ "$1" == "configure" ]; then
	# Link Clue Bridge packages by HomeBridge module
	if [ ! -h /opt/node/lib/node_modules/homebridge-clue ] && [ ! -f /opt/node/lib/node_modules/homebridge-clue ]; then
		ln -fs /opt/clue/share/bridge /opt/node/lib/node_modules/homebridge-clue
	fi

	# Set scripts permissions and Register service
	chmod +x /opt/clue/bin/bridge
	chmod +x /etc/init.d/clue-bridge
	/usr/sbin/update-rc.d clue-bridge defaults >/dev/null 2>&1
	/bin/systemctl daemon-reload >/dev/null 2>&1

	# Restart the service (if is the case)
	if [ $(ps -ef | grep "bridge" | grep -v "grep" | grep -v "apt" | grep -v "dpkg" | wc -l) -ne 0 ]; then
		service clue-bridge restart >/dev/null 2>&1
	fi
fi