#!/bin/bash

if [ "$1" == "remove" ] || [ "$1" == "purge" ]; then
	# Remove system resources
	rm -rf /opt/node/lib/node_modules/homebridge-clue

	# Remove profile resources
	if [ "$1" == "purge" ]; then
		rm -rf /root/.homebridge
	fi
fi