#!/bin/bash

if [ "$1" == "remove" ]; then
	# Remove service
	service clue-bridge stop >/dev/null 2>&1
	/usr/sbin/update-rc.d -f clue-bridge remove >/dev/null 2>&1
	/bin/systemctl daemon-reload >/dev/null 2>&1
fi